FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

# 1) зависимости
COPY src/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

# 2) код приложения
COPY src/ /app/

EXPOSE 8000

# 3) запуск через модуль Python (устойчиво к PATH)
CMD ["python","-m","uvicorn","api:app","--host","0.0.0.0","--port","8000","--proxy-headers"]
